# Generated by Django 4.2.7 on 2023-11-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_do_bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=500, verbose_name='id')),
                ('task', models.CharField(max_length=500)),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
