# Generated by Django 4.2.7 on 2023-11-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_to_do_bank_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_bank',
            name='id',
        ),
        migrations.AlterField(
            model_name='to_do_bank',
            name='key',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
